# Usando a imagem oficial do Node.js
FROM node:16-alpine

# Criando o diretório da aplicação dentro do container
WORKDIR /app

# Copiando o package.json e o package-lock.json (se existir)
COPY package*.json ./

# Instalando as dependências da aplicação
RUN npm install

# Copiando o restante do código da aplicação
COPY . .

# Expondo a porta em que a API vai rodar
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "run", "dev"]
